sudo: required
language: python
python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master
    - devel

env:
  - DOCKER_COMPOSE_VERSION=1.17.1

script:
  - docker-compose -f docker-compose.test.yml up

deploy:
  # deploy to staging enviroment
  - provider: script
    script: bash staging-deploy.sh
    on:
      branch: develop

  # deploy to production enviroment
  - provider: script
    script: bash production-deploy.sh
    on:
      branch: master
