version: '3'
services:
  # Server
  sdcurve-nginx:
    image: victorhad/sdcurve:nginx
    container_name: sdcurve-nginx
    ports:
      - "8000:8000"
    depends_on:
      - sdcurve-prod

  # Backend production enviroment
  sdcurve-prod:
    image: victorhad/sdcurve:latest
    container_name: sdcurve-prod
    depends_on:
      - db

  # Postgresql database
  db:
    image: postgres
    container_name: sdcurve-db
