version: '3'
services:
  # Production enviroment
  sdcurve-prod:
    image: victorhad/sdcurve:latest
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile

  # NGINX to production
  sdcurve-nginx:
    image: victorhad/sdcurve:nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
