version: '3'
services:
  # Server
  nginx-prod:
    image: victorhad/sdcurve:nginx
    ports:
      - "8000:8000"
    depends_on:
      - sdcurve-prod

  # Backend production enviroment
  sdcurve-prod:
    image: victorhad/sdcurve:latest
    depends_on:
      - db

  # Postgresql database
  db:
    image: postgres
